# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
#  config.vm.network :forwarded_port, guest: 137, host: 139
#  config.vm.network :forwarded_port, guest: 138, host: 139
#  config.vm.network :forwarded_port, guest: 139, host: 139
#  config.vm.network :forwarded_port, guest: 445, host: 445
  config.vm.network "private_network", ip: "192.168.50.4"


  # config.vm.provider "virtualbox" do |vb|
  #   vb.memory = "1024"
  # end

# TODO: move this to puppet provisioning
#    sudo cp /vagrant/smb.conf /etc/samba/smb.conf
#    sudo cp /vagrant/avahi*service /etc/avahi/services/
#
#    sudo /etc/init.d/messagebus   start
#    sudo /etc/init.d/smb          start
#    sudo /etc/init.d/avahi-daemon start

  # https://docs.vagrantup.com/v2/provisioning/puppet_apply.html
  config.vm.provision "puppet" do |puppet|
    puppet.options = "--verbose --debug"
  end

end
