# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "AndrewDryga/vagrant-box-osx"
  config.vm.network "private_network", ip: "192.168.50.10"
  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end
end
