# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.network "private_network", ip: "192.168.50.12"

  # https://docs.vagrantup.com/v2/provisioning/puppet_apply.html
  config.vm.provision "puppet" do |puppet|
    puppet.options = "--verbose --debug"
  end

end
