# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  (1..3).each do |i|
    config.vm.define vm_name = "kvm-server-#{i}" do |config|
      config.cache.scope = :box
      config.vm.hostname = vm_name
      ip = "172.21.12.#{i+10}"
      config.vm.network :private_network, ip: ip
      config.vm.provision :shell, :inline => "DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -yq qemu-kvm libvirt-bin ubuntu-vm-builder bridge-utils", :privileged => true
    end
  end
end
