# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.50.15"

  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    swapoff -a # https://github.com/kubernetes/kubernetes/issues/53533
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
    echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable" > /etc/apt/sources.list.d/docker.list
    echo "deb http://packages.cloud.google.com/apt cloud-sdk-xenial main" > /etc/apt/sources.list.d/google-cloud-sdk.list
    echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
    apt update
    apt dist-upgrade -y
    apt install -y apt-transport-https ca-certificates curl make software-properties-common
    apt install -y docker-ce
    usermod -aG docker vagrant
    apt install -y kubelet kubeadm kubectl
    kubeadm init
    mkdir ~vagrant/.kube
    cp /etc/kubernetes/admin.conf ~vagrant/.kube/config
    chown -R vagrant:vagrant ~vagrant
    kubectl taint nodes ubuntu-xenial node-role.kubernetes.io/master:NoSchedule-
  SHELL

end
