# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.50.13"

#  config.vm.provider "virtualbox" do |v|
#    v.gui = true
#  end

  config.vm.provision "shell", inline: <<-SHELL
    set -x
    export IP_ADDR=`ip route get 8.8.8.8 | awk '$1 == "8.8.8.8" {print $7}'`
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get dist-upgrade -y
    apt install -y python3 python3-pip

    # # Setup Docker
    # apt-get install -y apt-transport-https ca-certificates curl make software-properties-common
    # curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    # echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" > /etc/apt/sources.list.d/docker.list
    # apt-get update
    # apt-get install -y docker-ce
    # systemctl start docker
    # usermod -aG docker vagrant
    # pkill -u vagrant
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end


end
