# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.50.8"

#  config.vm.provider "virtualbox" do |v|
#    v.gui = true
#  end

#  config.vm.provision "shell", inline: <<-SHELL
#    export DEBIAN_FRONTEND=noninteractive
#    apt update
#    apt install -y python
#  SHELL

# https://www.vagrantup.com/docs/provisioning/ansible.html
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

#  config.vm.provision "shell", inline: <<-SHELL
#    export DEBIAN_FRONTEND=noninteractive
#    apt-get update
#    apt-get install -y puppet
#  SHELL
#
## https://www.vagrantup.com/docs/provisioning/puppet_apply.html
#  config.vm.provision "puppet" do |puppet|
#    puppet.options = "--verbose --debug"
#    puppet.manifests_path = "manifests"
#    puppet.manifest_file = "default.pp"
#  end

end
