# -*- mode: ruby -*-
# vi: set ft=ruby :
# <https://github.com/lavabit/robox>
# <https://app.vagrantup.com/lineage/boxes/lineage>
# <https://wiki.lineageos.org/devices/klimtwifi/build>
# TODO:
# - Figure out how to overide the default env vars for the following when running `vagrant up`:
#     DEVICE=klimtwifi
#     BRANCH=cm-14.1
#     VENDOR=samsung
#     NAME=Samsung Galaxy Tab S 8.4 Wi-Fi
#     EMAIL=dade.murphy@otv

Vagrant.configure(2) do |config|
  config.vm.box = "lineageos/lineage"
  config.vm.network "private_network", ip: "192.168.50.6"

  config.vm.provider "virtualbox" do |vb|
#    v.gui = true
    vb.memory = "8192"
    # This requires that the running user be in the vboxusers group.
    # Check `groups` to verify your groups, log out and back in after group modifications.
    # Check `vboxmanage list usbhost` for available devices.
    # Find your vendorid and paroductid with lsusb. XXXX:YYYY where XXXX is vendorid, YYYY is productid
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ['modifyvm', :id, '--usbxhci', 'on']
    vb.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'Samsung Galaxy Tab S 8.4 Wi-Fi', '--vendorid', '0x04e8', '--productid', '0x685d']
  end

#  config.vm.provision "shell", inline: <<-SHELL
#    apt-get update
#    DEBIAN_FRONTEND=noninteractive apt-get install -y \
#      ubuntu-desktop \
#      virtualbox-guest-dkms \
#      virtualbox-guest-utils \
#      virtualbox-guest-x11
#    shutdown -r +1
#  SHELL
end
