# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end
  config.vm.provision :shell, path: "setup.sh", privileged: true
  config.vm.provision :reload
end
