# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define vm_name = "puppet-server" do |config|
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "3072"
    end
    config.cache.scope = :box
    config.vm.hostname = "puppet-server"
    ip = "172.19.57.100"
    config.vm.network :private_network, ip: ip
    config.vm.provision :shell, path: "setup-puppet-server.sh", privileged: true
  end

  config.vm.define vm_name = "puppet-client" do |config|
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
    config.cache.scope = :box
    config.vm.hostname = vm_name
    ip = "172.19.57.101"
    config.vm.network :private_network, ip: ip
    config.vm.provision :shell, path: "setup-puppet-client.sh", privileged: true
  end

end

# vim: ai ts=2 sts=2 et sw=2 ft=ruby
# vim: autoindent tabstop=2 shiftwidth=2 expandtab softtabstop=2 filetype=ruby
