# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "suse/sles11sp3"
  config.vm.network "private_network", ip: "192.168.50.11"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

end
