# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "private_network", ip: "192.168.50.19"

#  config.vm.provider "virtualbox" do |v|
#    v.gui = true
#  end

#  config.vm.provision "shell", inline: <<-SHELL
#    export DEBIAN_FRONTEND=noninteractive
#    apt update
#    apt install -y build-essential
#  SHELL

#  config.vm.provision "ansible" do |ansible|
#    ansible.playbook = "playbook.yml"
#  end

end
