# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.50.8"


  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
      ubuntu-desktop \
      virtualbox-guest-dkms \
      virtualbox-guest-utils \
      virtualbox-guest-x11
      
  SHELL
end
