# -*- mode: ruby -*-
# vi: set ft=ruby :

# http://emulationstation.org/gettingstarted.html#install_deb

Vagrant.configure(2) do |config|

  config.vm.box = "debian/jessie64"
  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end
  config.vm.provision "shell", path: "setup.sh"

end
